// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAccount(arg1:main.Account):Promise<number>;

export function AddInstallment(arg1:main.Installment):Promise<number>;

export function AddTransaction(arg1:main.Transaction):Promise<number>;

export function AddTransfer(arg1:main.Transfer):Promise<number>;

export function AutoRestoreIfNeeded():Promise<boolean>;

export function BackupNow():Promise<void>;

export function Close():Promise<void>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteInstallment(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function DeleteTransfer(arg1:number):Promise<void>;

export function ExportCSV():Promise<void>;

export function ExportJSON():Promise<void>;

export function GetAccountBalances():Promise<Array<main.AccountBalance>>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetBackupConfig():Promise<main.BackupConfig>;

export function GetInstallments():Promise<Array<main.Installment>>;

export function GetNote(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetTransactions(arg1:string,arg2:string):Promise<Array<main.Transaction>>;

export function GetTransfers():Promise<Array<main.Transfer>>;

export function RestoreFromBackup():Promise<void>;

export function SaveBackupConfig(arg1:main.BackupConfig):Promise<void>;

export function SaveNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTransaction(arg1:main.Transaction):Promise<void>;
