// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoRestoreIfNeeded() {
  return window['go']['main']['App']['AutoRestoreIfNeeded']();
}

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function AddInstallment(arg1) {
  return window['go']['main']['App']['AddInstallment'](arg1);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function AddTransfer(arg1) {
  return window['go']['main']['App']['AddTransfer'](arg1);
}

export function BackupNow() {
  return window['go']['main']['App']['BackupNow']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function DeleteInstallment(arg1) {
  return window['go']['main']['App']['DeleteInstallment'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function DeleteTransfer(arg1) {
  return window['go']['main']['App']['DeleteTransfer'](arg1);
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function ExportJSON() {
  return window['go']['main']['App']['ExportJSON']();
}

export function GetAccountBalances() {
  return window['go']['main']['App']['GetAccountBalances']();
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBackupConfig() {
  return window['go']['main']['App']['GetBackupConfig']();
}

export function GetInstallments() {
  return window['go']['main']['App']['GetInstallments']();
}

export function GetNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNote'](arg1, arg2, arg3);
}

export function GetTransactions(arg1, arg2) {
  return window['go']['main']['App']['GetTransactions'](arg1, arg2);
}

export function GetTransfers() {
  return window['go']['main']['App']['GetTransfers']();
}

export function RestoreFromBackup() {
  return window['go']['main']['App']['RestoreFromBackup']();
}

export function SaveBackupConfig(arg1) {
  return window['go']['main']['App']['SaveBackupConfig'](arg1);
}

export function SaveNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3, arg4);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}
